package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Blog;
import com.ikkong.platform.service.BlogService;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class BlogServiceImpl extends BaseService<Blog> implements BlogService{

}
