package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.core.dao.Db;
import com.ikkong.platform.model.Career;
import com.ikkong.platform.model.Major;
import com.ikkong.platform.model.Student;
import com.ikkong.platform.service.CareerService;
import com.ikkong.platform.service.MajorService;
import com.ikkong.platform.service.StudentService;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class CareerServiceImpl extends BaseService<Career> implements CareerService{

	@Override
	public boolean saveRelation(String ids, String careerid) {
		Db dao = Db.init();
		dao.deleteByIds("yb_career_relation", "careerid", careerid);
		
		String sql = "";
		String insertSql = "";
		String union_all = "";
		String[] id = ids.split(",");
		for (int i = 0; i < id.length; i++) {
			union_all = (i < id.length - 1) ? " union all " : "";
			sql += " (select " + id[i] + " costreeid," + careerid + " careerid "
					+ ")" + union_all;
		}

		sql = "select i.* from (" + sql + ") i";
		insertSql = "insert into yb_career_relation(costreeid,careerid) ";

		int cnt = dao.update(insertSql + sql, null);
		return cnt > 0;
	}

}
