package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Flavor;
import com.ikkong.platform.service.FlavorService;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class FlavorServiceImpl extends BaseService<Flavor> implements FlavorService{

}
