package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Match;
import com.ikkong.platform.model.Mirror;
import com.ikkong.platform.model.Net;
import com.ikkong.platform.model.Project;
import com.ikkong.platform.model.Student;
import com.ikkong.platform.service.MatchService;
import com.ikkong.platform.service.MirrorService;
import com.ikkong.platform.service.NetService;
import com.ikkong.platform.service.ProjectService;
import com.ikkong.platform.service.StudentService;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class MatchServiceImpl extends BaseService<Match> implements MatchService{

}
