package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Student;
import com.ikkong.platform.service.StudentService;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class StudentServiceImpl extends BaseService<Student> implements StudentService{

}
