package com.ikkong.platform.controller;

import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.platform.meta.intercept.BlogIntercept;
import com.ikkong.platform.meta.intercept.CareerIntercept;
import com.ikkong.platform.meta.intercept.StudentIntercept;
import com.ikkong.platform.model.Blog;
import com.ikkong.platform.model.Career;
import com.ikkong.platform.model.Major;
import com.ikkong.platform.model.Mirror;
import com.ikkong.platform.model.Student;
import com.ikkong.platform.service.BlogService;
import com.ikkong.platform.service.CareerService;
import com.ikkong.platform.service.MajorService;
import com.ikkong.platform.service.MirrorService;
import com.ikkong.platform.service.StudentService;
import com.ikkong.platform.service.impl.BlogServiceImpl;
import com.ikkong.platform.service.impl.CareerServiceImpl;
import com.ikkong.platform.service.impl.MajorServiceImpl;
import com.ikkong.platform.service.impl.MirrorServiceImpl;
import com.ikkong.platform.service.impl.StudentServiceImpl;
import com.ikkong.system.controller.base.UrlPermissController;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.ehcache.CacheKit;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class CareerController extends UrlPermissController {
	private static String CODE = "career";
	private static String PERFIX = "yb_career";
	private static String LIST_SOURCE = "Career.list";
	private static String BASE_PATH = "/platform/career/";
	
	CareerService service = new CareerServiceImpl();
	
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "career.html");
		
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "career_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Career career = service.findById(id);
		setAttr("model", JsonKit.toJson(career));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "career_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Career career = service.findById(id);
		setAttr("model", JsonKit.toJson(career));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "career_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Career career = mapping(PERFIX, Career.class);
		boolean temp = service.save(career);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Career career = mapping(PERFIX, Career.class);
		boolean temp = service.update(career);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
	
	public void relation() {
		String id = getPara(0);
		Career career = service.findById(id);
		setAttr("careername", career.getCareer_name());
		setAttr("careerid", id);
		render(BASE_PATH + "career_relation.html");
	}
	
	public void saveRelation() {
		String ids = getPara("ids");
		String careerid = getPara("careerid");
		String[] id = ids.split(",");
		if (id.length <= 1) {
			CacheKit.removeAll(COURSE_TREE_CACHE);
			renderJson(success("设置成功"));
			return;
		}
		boolean temp = service.saveRelation(ids, careerid);
		if (temp) {
			CacheKit.removeAll(COURSE_TREE_CACHE);
			renderJson(success("设置成功"));
		} else {
			renderJson(error("设置失败"));
		}
	}
}
