package com.ikkong.platform.controller;

import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.platform.meta.intercept.BlogIntercept;
import com.ikkong.platform.meta.intercept.StudentIntercept;
import com.ikkong.platform.model.Blog;
import com.ikkong.platform.model.Mirror;
import com.ikkong.platform.model.Student;
import com.ikkong.platform.service.BlogService;
import com.ikkong.platform.service.MirrorService;
import com.ikkong.platform.service.StudentService;
import com.ikkong.platform.service.impl.BlogServiceImpl;
import com.ikkong.platform.service.impl.MirrorServiceImpl;
import com.ikkong.platform.service.impl.StudentServiceImpl;
import com.ikkong.system.controller.base.UrlPermissController;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class MirrorController extends UrlPermissController {
	private static String CODE = "mirror";
	private static String PERFIX = "yb_mirror";
	private static String LIST_SOURCE = "Mirror.list";
	private static String BASE_PATH = "/platform/mirror/";
	
	MirrorService service = new MirrorServiceImpl();
	
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "mirror.html");
		
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "mirror_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Mirror mirror = service.findById(id);
		setAttr("model", JsonKit.toJson(mirror));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "mirror_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Mirror mirror = service.findById(id);
		setAttr("model", JsonKit.toJson(mirror));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "mirror_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Mirror mirror = mapping(PERFIX, Mirror.class);
		boolean temp = service.save(mirror);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Mirror mirror = mapping(PERFIX, Mirror.class);
		boolean temp = service.update(mirror);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
