package com.ikkong.platform.controller;

import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.platform.meta.intercept.BlogIntercept;
import com.ikkong.platform.meta.intercept.StudentIntercept;
import com.ikkong.platform.model.Blog;
import com.ikkong.platform.model.Mirror;
import com.ikkong.platform.model.Net;
import com.ikkong.platform.model.Student;
import com.ikkong.platform.service.BlogService;
import com.ikkong.platform.service.MirrorService;
import com.ikkong.platform.service.NetService;
import com.ikkong.platform.service.StudentService;
import com.ikkong.platform.service.impl.BlogServiceImpl;
import com.ikkong.platform.service.impl.MirrorServiceImpl;
import com.ikkong.platform.service.impl.NetServiceImpl;
import com.ikkong.platform.service.impl.StudentServiceImpl;
import com.ikkong.system.controller.base.UrlPermissController;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class NetController extends UrlPermissController {
	private static String CODE = "net";
	private static String PERFIX = "yb_net";
	private static String LIST_SOURCE = "Net.list";
	private static String BASE_PATH = "/platform/net/";
	
	NetService service = new NetServiceImpl();
	
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "net.html");
		
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "net_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Net net = service.findById(id);
		setAttr("model", JsonKit.toJson(net));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "net_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Net net = service.findById(id);
		setAttr("model", JsonKit.toJson(net));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "net_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Net net = mapping(PERFIX, Net.class);
		boolean temp = service.save(net);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Net net = mapping(PERFIX, Net.class);
		boolean temp = service.update(net);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
