package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "tb_tfw_blog")
@BindID(name = "f_it_id")
@SuppressWarnings("serial")
public class Blog extends BaseModel {

	// 主键
	private Integer f_it_id;
	// 状态
	private Integer f_it_del;
	// 排序
	private Integer f_it_seq;
	// 内容
	private String f_it_content;
	// 标题
	private String f_it_title;
	// 创建时间
	private Date f_it_createtime;

	private int version;

	@AutoID
	public Integer getF_it_id() {
		return f_it_id;
	}

	public void setF_it_id(Integer f_it_id) {
		this.f_it_id = f_it_id;
	}

	public Integer getF_it_del() {
		return f_it_del;
	}

	public void setF_it_del(Integer f_it_del) {
		this.f_it_del = f_it_del;
	}

	public Integer getF_it_seq() {
		return f_it_seq;
	}

	public void setF_it_seq(Integer f_it_seq) {
		this.f_it_seq = f_it_seq;
	}

	public String getF_it_content() {
		return f_it_content;
	}

	public void setF_it_content(String f_it_content) {
		this.f_it_content = f_it_content;
	}

	public String getF_it_title() {
		return f_it_title;
	}

	public void setF_it_title(String f_it_title) {
		this.f_it_title = f_it_title;
	}

	public Date getF_it_createtime() {
		return f_it_createtime;
	}

	public void setF_it_createtime(Date f_it_createtime) {
		this.f_it_createtime = f_it_createtime;
	}

	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

}
