package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_career")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Career extends BaseModel {

	// 主键
	private Integer id;
	// 编码
	private String career_code;
	// 专业名
	private String career_name;
	
	private String image_url;


	
	public String getCareer_code() {
		return career_code;
	}
	public void setCareer_code(String career_code) {
		this.career_code = career_code;
	}
	public String getCareer_name() {
		return career_name;
	}
	public void setCareer_name(String career_name) {
		this.career_name = career_name;
	}
	public String getImage_url() {
		return image_url;
	}
	public void setImage_url(String image_url) {
		this.image_url = image_url;
	}
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

}
