package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_clazz")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Clazz extends BaseModel {

	// 主键
	private Integer id;
	// 编码
	private String clazz_code;
	// 专业名
	private String clazz_name;
	
	private String clazz_grade;

	
	public String getClazz_code() {
		return clazz_code;
	}
	public void setClazz_code(String clazz_code) {
		this.clazz_code = clazz_code;
	}
	public String getClazz_name() {
		return clazz_name;
	}
	public void setClazz_name(String clazz_name) {
		this.clazz_name = clazz_name;
	}
	public String getClazz_grade() {
		return clazz_grade;
	}
	public void setClazz_grade(String clazz_grade) {
		this.clazz_grade = clazz_grade;
	}
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	
}
