<<<<<<< HEAD
package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_flavor")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Flavor extends BaseModel {

	// 主键
	private Integer id;
	// 编码
	private String flavor_code;
	// 专业名
	private String flavor_name;
	
	private String flavor_describe;
	
	public String getFlavor_code() {
		return flavor_code;
	}
	public void setFlavor_code(String flavor_code) {
		this.flavor_code = flavor_code;
	}
	public String getFlavor_name() {
		return flavor_name;
	}
	public void setFlavor_name(String flavor_name) {
		this.flavor_name = flavor_name;
	}
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getFlavor_describe() {
		return flavor_describe;
	}
	public void setFlavor_describe(String flavor_describe) {
		this.flavor_describe = flavor_describe;
	}
	
	
}
=======
package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_flavor")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Flavor extends BaseModel {

	// 主键
	private Integer id;
	// 编码
	private String flavor_code;
	// 专业名
	private String flavor_name;
<<<<<<< HEAD
	
	private String flavor_describe;
	


=======
	private String flavor_describe;
	
>>>>>>> 8cda401d6fe7aeecf6706d1e45e3e8a09f7cb919
	
	public String getFlavor_describe() {
		return flavor_describe;
	}
	public void setFlavor_describe(String flavor_describe) {
		this.flavor_describe = flavor_describe;
	}
	public String getFlavor_code() {
		return flavor_code;
	}
	public void setFlavor_code(String flavor_code) {
		this.flavor_code = flavor_code;
	}
	public String getFlavor_name() {
		return flavor_name;
	}
	public void setFlavor_name(String flavor_name) {
		this.flavor_name = flavor_name;
	}
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getFlavor_describe() {
		return flavor_describe;
	}
	public void setFlavor_describe(String flavor_describe) {
		this.flavor_describe = flavor_describe;
	}
	
	
}
>>>>>>> 8dc856ce4cf71a316e075dfbefc63d2b2275711b
