package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_flavor")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Flavor extends BaseModel {

	// 主键
	private Integer id;
	// 编码
	private String flavor_code;
	// 专业名
	private String flavor_name;


	
	public String getFlavor_code() {
		return flavor_code;
	}
	public void setFlavor_code(String flavor_code) {
		this.flavor_code = flavor_code;
	}
	public String getFlavor_name() {
		return flavor_name;
	}
	public void setFlavor_name(String flavor_name) {
		this.flavor_name = flavor_name;
	}
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	
}
