package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_net")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Net extends BaseModel {

	// 主键
	private Integer id;
	// 编码
	private String net_code;
	// 专业名
	private String net_name;


	
	public String getNet_code() {
		return net_code;
	}
	public void setNet_code(String net_code) {
		this.net_code = net_code;
	}
	public String getNet_name() {
		return net_name;
	}
	public void setNet_name(String net_name) {
		this.net_name = net_name;
	}
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	
}
