package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_project")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Project extends BaseModel {

	// 主键
	private Integer id;
	// 姓名
	private String project_name;
	private Integer mirrorid;
	private Integer netid;
	private Integer flavorid;
	private Integer industryid;
	private String doc_url;
	private String image_url;
	private Date create_time;
	private Integer status;
	
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	
	public String getProject_name() {
		return project_name;
	}
	public void setProject_name(String project_name) {
		this.project_name = project_name;
	}
	public Integer getMirrorid() {
		return mirrorid;
	}
	public void setMirrorid(Integer mirrorid) {
		this.mirrorid = mirrorid;
	}

	public Integer getNetid() {
		return netid;
	}
	public void setNetid(Integer netid) {
		this.netid = netid;
	}
	
	public Integer getIndustryid() {
		return industryid;
	}
	public void setIndustryid(Integer industryid) {
		this.industryid = industryid;
	}
	public String getDoc_url() {
		return doc_url;
	}
	public void setDoc_url(String doc_url) {
		this.doc_url = doc_url;
	}
	public Integer getFlavorid() {
		return flavorid;
	}
	public void setFlavorid(Integer flavorid) {
		this.flavorid = flavorid;
	}
	public String getImage_url() {
		return image_url;
	}
	public void setImage_url(String image_url) {
		this.image_url = image_url;
	}
	public Date getCreate_time() {
		return create_time;
	}
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}


}
