package com.ikkong.platform.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2016-10-08 15:59:45
 */
@Table(name = "yb_student")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Student extends BaseModel {

	// 主键
	private Integer id;
	// 姓名
	private String user_name;
	// 密码
	private String user_password;
	// 班级
	private String clazz_id;
	// 专业
	private Integer majorid;
	
	@AutoID
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getUser_name() {
		return user_name;
	}
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	public String getUser_password() {
		return user_password;
	}
	public void setUser_password(String user_password) {
		this.user_password = user_password;
	}
	
	public String getClazz_id() {
		return clazz_id;
	}
	public void setClazz_id(String clazz_id) {
		this.clazz_id = clazz_id;
	}
	public Integer getMajorid() {
		return majorid;
	}
	public void setMajorid(Integer majorid) {
		this.majorid = majorid;
	}

}
