package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Blog;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public interface BlogService extends IService<Blog>{

}
