package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Blog;
import com.ikkong.platform.model.Flavor;
import com.ikkong.platform.model.Mirror;
import com.ikkong.platform.model.Net;
import com.ikkong.platform.model.Student;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public interface FlavorService extends IService<Flavor>{

}
