package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Blog;
import com.ikkong.platform.model.Major;
import com.ikkong.platform.model.Match;
import com.ikkong.platform.model.Project;
import com.ikkong.platform.model.Student;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public interface MatchService extends IService<Match>{

}
