package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Blog;
import com.ikkong.platform.model.Student;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public interface StudentService extends IService<Student>{

}
